Permit mintette
input-output-hk/rscoin-core pull request #1
Opened 2016-09-16 22:18 UTC by domenkozar

2016-09-19 10:09 UTC, gromakovsky commented on src/RSCoin/Core/Communication.hs
> +    -> String
Instead of passing `String` and `Int` you'd better pass `RSCoin.Core.Types.Mintette` which consists of exactly `String` and `Int`.

2016-09-19 10:10 UTC, gromakovsky commented on src/RSCoin/Core/Communication.hs
> +    let signed = mkWithSignature mintetteSK (host, port)
The idea was to sign mintette's public key also.

2016-09-19 10:14 UTC, gromakovsky requested changes

2016-09-19 10:20 UTC, domenkozar commented on src/RSCoin/Core/Communication.hs
> +    let signed = mkWithSignature mintetteSK (host, port)
@gromakovsky What's the purpose signing the public key? 

If the signature can be verified, then the public key already stored proved that owner has the corresponding private key.

2016-09-19 10:33 UTC, domenkozar commented on src/RSCoin/Core/Communication.hs
> +    -> String
Thanks, will fix!

2016-09-19 10:56 UTC, gromakovsky commented on src/RSCoin/Core/Communication.hs
> +    let signed = mkWithSignature mintetteSK (host, port)
Ok, my bad, I agree there is no reason to do it. Then there is only one simple thing to fix in `rscoin-core`.

2016-09-20 18:54 UTC, gromakovsky approved these changes

2016-09-20 19:22 UTC, gromakovsky commented
Merged after rebase.

2016-09-20 19:22 UTC, closed without merging

2021-01-19 05:45 UTC, Virginiakk reviewed
N